package com.alexb.iterators;

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * Generates proper divisors of the input number.
 * <p>
 * Divisors are generated by symmetric pairs rather than in natural order.
 * <p>
 * 6 -> 1 2 3 <br>
 * 12 -> 1 2 6 3 4
 */
public class DivisorsIterator implements Iterator<Long> {
    private final long x;
    private final long sqrtX;
    private long i = 1;
    private long j = 0;

    /**
     * @param x the input number
     */
    public DivisorsIterator(long x) {
        this.x = x;
        this.sqrtX = (long) Math.sqrt(x);
        if (x == 1) {
            i = Long.MAX_VALUE; // 1 has no proper divisors
        }
    }

    @Override
    public boolean hasNext() {
        return i <= sqrtX || j != 0;
    }

    @Override
    public Long next() {
        if (i > sqrtX && j == 0) {
            throw new NoSuchElementException();
        }
        long result;
        if (j == 0) {
            result = i;
            j = x / i;
            if (j == x || j == i) {
                j = 0;
            }
            do {
                i++;
            } while (x % i != 0 && i <= sqrtX);
        } else {
            result = j;
            j = 0;
        }
        return result;
    }
}
